"""tags

Revision ID: 0dc02392a27c
Revises: 902226065b4b
Create Date: 2016-11-16 00:48:18.554224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc02392a27c'
down_revision = '902226065b4b'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.Column('nm_tag', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id_tag')
    )
    op.create_index(op.f('ix_tag_nm_tag'), 'tag', ['nm_tag'], unique=True)
    op.create_table('bookmark_tag',
    sa.Column('id_tad', sa.Integer(), nullable=False),
    sa.Column('id_bookmark', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_bookmark'], ['bookmark.id_bookmark'], ),
    sa.ForeignKeyConstraint(['id_tad'], ['tag.id_tag'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark_tag')
    op.drop_index(op.f('ix_tag_nm_tag'), table_name='tag')
    op.drop_table('tag')
    ### end Alembic commands ###
