"""initial

Revision ID: 902226065b4b
Revises: 
Create Date: 2016-11-16 00:24:33.708094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902226065b4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nm_firstName', sa.String(length=120), nullable=False),
    sa.Column('nm_lastName', sa.String(length=120), nullable=False),
    sa.Column('nm_userName', sa.String(length=80), nullable=True),
    sa.Column('nm_passwordHash', sa.String(), nullable=True),
    sa.Column('nm_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('nm_email'),
    sa.UniqueConstraint('nm_userName')
    )
    op.create_table('bookmark',
    sa.Column('id_bookmark', sa.Integer(), nullable=False),
    sa.Column('nm_url', sa.Text(), nullable=False),
    sa.Column('dt_bookmark', sa.DateTime(), nullable=True),
    sa.Column('nm_description', sa.String(length=300), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_bookmark')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark')
    op.drop_table('user')
    ### end Alembic commands ###
